/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BookmarkObservation struct {

	// Custom error page URL
	AccessibilityErrorRedirectURL *string `json:"accessibilityErrorRedirectUrl,omitempty" tf:"accessibility_error_redirect_url,omitempty"`

	// Custom login page URL
	AccessibilityLoginRedirectURL *string `json:"accessibilityLoginRedirectUrl,omitempty" tf:"accessibility_login_redirect_url,omitempty"`

	// Enable self service
	AccessibilitySelfService *bool `json:"accessibilitySelfService,omitempty" tf:"accessibility_self_service,omitempty"`

	// Application notes for admins.
	AdminNote *string `json:"adminNote,omitempty" tf:"admin_note,omitempty"`

	// Displays specific appLinks for the app
	AppLinksJSON *string `json:"appLinksJson,omitempty" tf:"app_links_json,omitempty"`

	// Id of this apps authentication policy
	AuthenticationPolicy *string `json:"authenticationPolicy,omitempty" tf:"authentication_policy,omitempty"`

	// Display auto submit toolbar
	AutoSubmitToolbar *bool `json:"autoSubmitToolbar,omitempty" tf:"auto_submit_toolbar,omitempty"`

	// Application notes for end users.
	EnduserNote *string `json:"enduserNote,omitempty" tf:"enduser_note,omitempty"`

	// Do not display application icon on mobile app
	HideIos *bool `json:"hideIos,omitempty" tf:"hide_ios,omitempty"`

	// Do not display application icon to users
	HideWeb *bool `json:"hideWeb,omitempty" tf:"hide_web,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Pretty name of app.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// Local path to logo of the application.
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// URL of the application's logo
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// Name of the app.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Would you like Okta to add an integration for this app?
	RequestIntegration *bool `json:"requestIntegration,omitempty" tf:"request_integration,omitempty"`

	// Sign on mode of application.
	SignOnMode *string `json:"signOnMode,omitempty" tf:"sign_on_mode,omitempty"`

	// Status of application.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type BookmarkParameters struct {

	// Custom error page URL
	// +kubebuilder:validation:Optional
	AccessibilityErrorRedirectURL *string `json:"accessibilityErrorRedirectUrl,omitempty" tf:"accessibility_error_redirect_url,omitempty"`

	// Custom login page URL
	// +kubebuilder:validation:Optional
	AccessibilityLoginRedirectURL *string `json:"accessibilityLoginRedirectUrl,omitempty" tf:"accessibility_login_redirect_url,omitempty"`

	// Enable self service
	// +kubebuilder:validation:Optional
	AccessibilitySelfService *bool `json:"accessibilitySelfService,omitempty" tf:"accessibility_self_service,omitempty"`

	// Application notes for admins.
	// +kubebuilder:validation:Optional
	AdminNote *string `json:"adminNote,omitempty" tf:"admin_note,omitempty"`

	// Displays specific appLinks for the app
	// +kubebuilder:validation:Optional
	AppLinksJSON *string `json:"appLinksJson,omitempty" tf:"app_links_json,omitempty"`

	// Id of this apps authentication policy
	// +kubebuilder:validation:Optional
	AuthenticationPolicy *string `json:"authenticationPolicy,omitempty" tf:"authentication_policy,omitempty"`

	// Display auto submit toolbar
	// +kubebuilder:validation:Optional
	AutoSubmitToolbar *bool `json:"autoSubmitToolbar,omitempty" tf:"auto_submit_toolbar,omitempty"`

	// Application notes for end users.
	// +kubebuilder:validation:Optional
	EnduserNote *string `json:"enduserNote,omitempty" tf:"enduser_note,omitempty"`

	// Do not display application icon on mobile app
	// +kubebuilder:validation:Optional
	HideIos *bool `json:"hideIos,omitempty" tf:"hide_ios,omitempty"`

	// Do not display application icon to users
	// +kubebuilder:validation:Optional
	HideWeb *bool `json:"hideWeb,omitempty" tf:"hide_web,omitempty"`

	// Pretty name of app.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// Local path to logo of the application.
	// +kubebuilder:validation:Optional
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Would you like Okta to add an integration for this app?
	// +kubebuilder:validation:Optional
	RequestIntegration *bool `json:"requestIntegration,omitempty" tf:"request_integration,omitempty"`

	// Status of application.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

// BookmarkSpec defines the desired state of Bookmark
type BookmarkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BookmarkParameters `json:"forProvider"`
}

// BookmarkStatus defines the observed state of Bookmark.
type BookmarkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BookmarkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Bookmark is the Schema for the Bookmarks API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,okta}
type Bookmark struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.label)",message="label is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.url)",message="url is a required parameter"
	Spec   BookmarkSpec   `json:"spec"`
	Status BookmarkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BookmarkList contains a list of Bookmarks
type BookmarkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Bookmark `json:"items"`
}

// Repository type metadata.
var (
	Bookmark_Kind             = "Bookmark"
	Bookmark_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Bookmark_Kind}.String()
	Bookmark_KindAPIVersion   = Bookmark_Kind + "." + CRDGroupVersion.String()
	Bookmark_GroupVersionKind = CRDGroupVersion.WithKind(Bookmark_Kind)
)

func init() {
	SchemeBuilder.Register(&Bookmark{}, &BookmarkList{})
}
