/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServerClaimDefaultObservation struct {

	// Specifies whether to include claims in token.
	AlwaysIncludeInToken *bool `json:"alwaysIncludeInToken,omitempty" tf:"always_include_in_token,omitempty"`

	// Auth server ID
	AuthServerID *string `json:"authServerId,omitempty" tf:"auth_server_id,omitempty"`

	// Specifies whether the claim is for an access token `RESOURCE` or ID token `IDENTITY`.
	ClaimType *string `json:"claimType,omitempty" tf:"claim_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Default auth server claim name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Auth server claim list of scopes
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// The status of the application.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The value of the claim.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// The type of value of the claim.
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`
}

type ServerClaimDefaultParameters struct {

	// Specifies whether to include claims in token.
	// +kubebuilder:validation:Optional
	AlwaysIncludeInToken *bool `json:"alwaysIncludeInToken,omitempty" tf:"always_include_in_token,omitempty"`

	// Auth server ID
	// +crossplane:generate:reference:type=github.com/healthcarecom/provider-okta/apis/auth/v1alpha1.Server
	// +crossplane:generate:reference:extractor=github.com/healthcarecom/provider-okta/apis/auth/v1alpha1.AuthServerID()
	// +kubebuilder:validation:Optional
	AuthServerID *string `json:"authServerId,omitempty" tf:"auth_server_id,omitempty"`

	// Reference to a Server in auth to populate authServerId.
	// +kubebuilder:validation:Optional
	AuthServerIDRef *v1.Reference `json:"authServerIdRef,omitempty" tf:"-"`

	// Selector for a Server in auth to populate authServerId.
	// +kubebuilder:validation:Optional
	AuthServerIDSelector *v1.Selector `json:"authServerIdSelector,omitempty" tf:"-"`

	// Default auth server claim name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the claim.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// ServerClaimDefaultSpec defines the desired state of ServerClaimDefault
type ServerClaimDefaultSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerClaimDefaultParameters `json:"forProvider"`
}

// ServerClaimDefaultStatus defines the observed state of ServerClaimDefault.
type ServerClaimDefaultStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerClaimDefaultObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ServerClaimDefault is the Schema for the ServerClaimDefaults API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,okta}
type ServerClaimDefault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	Spec   ServerClaimDefaultSpec   `json:"spec"`
	Status ServerClaimDefaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerClaimDefaultList contains a list of ServerClaimDefaults
type ServerClaimDefaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerClaimDefault `json:"items"`
}

// Repository type metadata.
var (
	ServerClaimDefault_Kind             = "ServerClaimDefault"
	ServerClaimDefault_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerClaimDefault_Kind}.String()
	ServerClaimDefault_KindAPIVersion   = ServerClaimDefault_Kind + "." + CRDGroupVersion.String()
	ServerClaimDefault_GroupVersionKind = CRDGroupVersion.WithKind(ServerClaimDefault_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerClaimDefault{}, &ServerClaimDefaultList{})
}
