/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServerDefaultObservation struct {

	// Currently Okta only supports a single value here
	Audiences []*string `json:"audiences,omitempty" tf:"audiences,omitempty"`

	// The timestamp when the authorization server started to use the `kid` for signing tokens.
	CredentialsLastRotated *string `json:"credentialsLastRotated,omitempty" tf:"credentials_last_rotated,omitempty"`

	// The timestamp when the authorization server changes the key for signing tokens. Only returned when `credentials_rotation_mode` is `AUTO`.
	CredentialsNextRotation *string `json:"credentialsNextRotation,omitempty" tf:"credentials_next_rotation,omitempty"`

	// Credential rotation mode, in many cases you cannot set this to MANUAL, the API will ignore the value and you will get a perpetual diff. This should rarely be used.
	CredentialsRotationMode *string `json:"credentialsRotationMode,omitempty" tf:"credentials_rotation_mode,omitempty"`

	// The description of the authorization server.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// allows you to use a custom issuer URL
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// *Early Access Property*. Indicates which value is specified in the issuer of the tokens that a Custom Authorization Server returns: the original Okta org domain URL or a custom domain URL
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// The ID of the JSON Web Key used for signing tokens issued by the authorization server.
	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	// The name of the authorization server. Not necessary but left for backwards capacity with legacy implementation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ServerDefaultParameters struct {

	// Currently Okta only supports a single value here
	// +kubebuilder:validation:Optional
	Audiences []*string `json:"audiences,omitempty" tf:"audiences,omitempty"`

	// Credential rotation mode, in many cases you cannot set this to MANUAL, the API will ignore the value and you will get a perpetual diff. This should rarely be used.
	// +kubebuilder:validation:Optional
	CredentialsRotationMode *string `json:"credentialsRotationMode,omitempty" tf:"credentials_rotation_mode,omitempty"`

	// The description of the authorization server.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// *Early Access Property*. Indicates which value is specified in the issuer of the tokens that a Custom Authorization Server returns: the original Okta org domain URL or a custom domain URL
	// +kubebuilder:validation:Optional
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// The name of the authorization server. Not necessary but left for backwards capacity with legacy implementation.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

// ServerDefaultSpec defines the desired state of ServerDefault
type ServerDefaultSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerDefaultParameters `json:"forProvider"`
}

// ServerDefaultStatus defines the observed state of ServerDefault.
type ServerDefaultStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerDefaultObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ServerDefault is the Schema for the ServerDefaults API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,okta}
type ServerDefault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ServerDefaultSpec   `json:"spec"`
	Status            ServerDefaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerDefaultList contains a list of ServerDefaults
type ServerDefaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerDefault `json:"items"`
}

// Repository type metadata.
var (
	ServerDefault_Kind             = "ServerDefault"
	ServerDefault_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerDefault_Kind}.String()
	ServerDefault_KindAPIVersion   = ServerDefault_Kind + "." + CRDGroupVersion.String()
	ServerDefault_GroupVersionKind = CRDGroupVersion.WithKind(ServerDefault_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerDefault{}, &ServerDefaultList{})
}
